name: GH Pages Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Setup Leaflet Example
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - uses: actions/checkout@v1
    - name: Deploy To gh-pages branch
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: .
